export enum Status {
    WAIT_FOR_IST_DELIVERY = "WAIT_FOR_IST_DELIVERY",
    WAIT_TEH_DELIVERY = "WAIT_TEH_DELIVERY",
    CUSTOMER_DELIVERED = "CUSTOMER_DELIVERED",
    WAIT_FOR_CARGO = "WAIT_FOR_CARGO",
    WAIT_CUSTOMER_DELIVERY = "WAIT_CUSTOMER_DELIVERY",
    CANCELED = "CANCELED"
}
